#!/usr/bin/env bash
# script shows numbers from 1 to 100 but,
# prints "FizzBuzz" when the number is a multiple of 3 and 5.
# prints "Fizz" when the number is only a multiple of 3.
# prints "Buzz" when the number is a multiple of 5.

for i in {1..100}
do
  if (( i % 3 == 0 && i % 5 == 0 ))
  then
    echo "FizzBuzz"
  elif (( i % 3 == 0 ))
  then
    echo "Fizz"
  elif (( i % 5 == 0 ))
  then
    echo "Buzz"
  else
    echo "$i"
  fi
done
