#!/usr/bin/env bash
# Display the contents of the file `/etc/passwd`
# Display the username, user id
# and user home directory path.

while read line; do
	echo "$line" | cut -d ':' -f1,3,6
done < /etc/passwd
