#!/usr/bin/env bash
# Bash script loops from 1 to 10 and,
#   display "bad luck" for the 4th loop iteration
#   display "good luck" for the 8th iteration
#   display "Holberton School" for all other iterations

i=0

while [ $i -lt 10 ]
do
  if [ $i -eq 3 ]
  then
    echo "bad luck"
  elif [ $i -eq 7 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( i++ ))
done
