#!/usr/bin/env bash
# bash script that display time for 12 horus and 59 minutes.
# hours from 0 to 12
# minutes from 1 to 59

hours=0

while [ $hours -le 12 ]
do
  echo "Hour: $hours"
  minutes=1
  while [ $minutes -le 59 ]
  do
    echo "$minutes"
    (( minutes++ ))
  done
  (( hours++ ))
done
